Fix dependency of xcb-image on xcb-util
Considering this linker error, xcb-image apparently depends on xcb-util:
```
/usr/bin/ld: /usr/static-compat/lib/libxcb-image.a(xcb_image.o): in function `xcb_create_pixmap_from_bitmap_data':
(.text+0x14b7): undefined reference to `xcb_aux_create_gc'
```

Change-Id: Ic87a94ec664c126a5af1012d31b068d3dc7ec947